#!/bin/bash -l

# Batch script to run a serial job on Legion with the upgraded
# software stack under SGE.

# 1. Force bash as the executing shell.
#$ -S /bin/bash

# 2. Request ten minutes of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=0:02:0

# 3. Request 1 gigabyte of RAM 
#$ -l mem=16G

# 4. Request 15 gigabyte of TMPDIR space (default is 10 GB)
#$ -l tmpfs=15G

# 5. Set the name of the job.
#$ -N multiqc

cd $TMPDIR

wd=$1

# 8. Run the application.
multiqc  $wd


tar zcvf $wd/multiqc.tar.gz $TMPDIR
# 9. Preferably, tar-up (archive) all output files onto the shared scratch area
tar zcvf $HOME/Scratch/files_from_job_$JOB_ID.tar.gz $TMPDIR

# Make sure you have given enough time for the copy to complete!


