#!/bin/bash -l
# Batch script to run a serial job on Legion with the upgraded
# software stack under SGE.
# 1. Force bash as the executing shell.
#$ -S /bin/bash
# 2. Request 6 hours of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=2:00:0
# 3. Request 4G of ram
#$ -l mem=4G
# 4. Request 40 gigabyte of TMPDIR space (default is 10 GB)
#$ -l tmpfs=10G
# 5. Set the name of the job.
#$ -N blacklist
# 6 join output streams
#$ -j yes
# 7 export job environment
#$ -V
#===========================
# blacklist for atacseq
#===========================

cd "$TMPDIR" || exit

wd=$1
narrowpeak=$2

cp "$wd"/"$narrowpeak" .

filtered_peak="${narrowpeak:0:${#narrowpeak}-3}".filt.gz    
blacklist="/home/sejjctj/Scratch/reference/grch38/chipseq_blacklist/hg38.blacklist.bed.gz"

bedtools intersect -v -a "$narrowpeak" -b "$blacklist" \
   		 | awk 'BEGIN{OFS="\t"} {if ($5>1000) $5=1000; print $0}' \
   		 | grep -P 'chr[\dXY]+[ \t]'  | gzip -nc > "$filtered_peak"

mv "$filtered_peak"  "$wd"
